<div data-bind="scope: 'koexample'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "koexample": {
                        "component": "AAllen_KnockOut/js/koexample",
                        "template": "AAllen_KnockOut/kotemplate"
                    }
                }
            }
        }
    }
</script>