

<div data-mage-init='
{
    "AAllen_Sandbox/js/child": {
        "test": 12
    }
}
'></div>

<div>
    <?php echo $block->getPayment() ?>
</div>

<div>
    <?php $block->inCart(2) ?>
</div>

<div>
    <?php echo $block->getPrice() ?>
</div>

<div>
    <?php $block->getProductNames() ?>
</div>

<form class="form" action="result" method="post">

    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Test Form') ?></span></legend><br>
        <div class="field required">
            <label for="number" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Input') ?></span>
            </label>

            <div class="control">
                <input type="text" id="number"
                       name="number"
                       class="input-text">
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>

</form>


<script type="text/x-magento-init">
    {
        "*": {
            "AAllen_Sandbox/js/sand": {
                "var1" : "<?php echo 'Hello from template' ?>"
            }
        }
    }
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "AAllen_Sandbox/js/galleri": {
            }
        }
    }
</script>