<?php
/**
 * Created by PhpStorm.
 * User: Aaron Allen
 * Date: 6/30/2016
 * Time: 2:29 AM
 */

namespace AAllen\MenuAnimate\Block\Html;

use Magento\Store\Model\ScopeInterface;

/**
 * Class Topmenu used for getting config values
 * @package AAllen\MenuAnimate\Block
 */
class Topmenu extends \Magento\Theme\Block\Html\Topmenu
{
    protected $_storeScope;

    public function _construct()
    {
        $this->_storeScope = ScopeInterface::SCOPE_STORE;
        $this->setTemplate('AAllen_MenuAnimate::html/topmenu.phtml');

        parent::_construct(); // TODO: Change the autogenerated stub
    }

    /**
     * Get speed
     * 
     * @return int
     */
    public function getSpeed()
    {
        return $this->_scopeConfig->getValue('design/menu_animation/speed', $this->_storeScope);
    }

    /**
     * Get toggle
     * 
     * @return bool
     */
    public function getToggle()
    {
        return $this->_scopeConfig->getValue('design/menu_animation/toggle', $this->_storeScope) == '1';
    }

    /**
     * Get delay
     * 
     * @return int
     */
    public function getDelay()
    {
        return $this->_scopeConfig->getValue('design/menu_animation/delay', $this->_storeScope);
    }
}