<?php
/** @var \AAllen\Showcase\Block\Widget\Showcase $block */
$block
?>

<div>
    <?php foreach ($block->getTabs() as $tab): ?>
        <button type="button" data-mage-init='
        {
            "AAllen_Showcase/js/showcase": {
                "conditions": "<?php echo $tab['conditions'] ?>",
                "tabIndex": "<?php echo $tab['tab_index'] ?>",
                "contentDiv": "#showcase-content",
                "defaultTab": {
                    "id": "<?php echo $block->getDefaultTabId() ?>"
                }
            }
        }
        '>
            <span><?php echo $tab['name'] ?></span>
        </button>
    <?php endforeach; ?>

    <div id="showcase-content">
        <?php echo $block->getDefaultHtml() ?>
    </div>
</div>

