<?php
/** @var \AAllen\Showcase\Block\Showcase $block */
$block
?>

<div>
    <?php $categories = $block->getCategories() ?>
    <?php foreach ($categories as $category): ?>
        <button type="button" data-mage-init='
        {
            "AAllen_CatMenu/js/cat-menu": {
                "contentDiv": "#contentDiv",
                "categoryId": "<?php echo $category->getId() ?>"
            }
        }
        '>
            <span><?php echo __($category->getName()) ?></span>
        </button>
    <?php endforeach; ?>
</div>

<div id="contentDiv" data-role="loader">
    <?php echo $block->getWidgetHtml() ?>
</div>
