<?php
/**
 * Created by PhpStorm.
 * User: Aaron Allen
 * Date: 3/12/2017
 * Time: 5:49 AM
 */

namespace AAllen\FixThirdCat\Block;


use Magento\Directory\Helper\Data;
use Magento\Framework\Data\Helper\PostHelper;
use Magento\Framework\Encryption\UrlCoder;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Element\Text;
use Magento\Store\Block\Switcher;
use Magento\Store\Model\Store;
use Magento\Store\Model\StoreManagerInterface;
use Magento\UrlRewrite\Model\UrlFinderInterface;
use Magento\Framework\Url\Helper\Data as UrlHelper;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use Magento\Framework\App\ActionInterface;

class Url extends Switcher
{
    protected $urlFinder;
    protected $urlHelper;

    protected $urlModifier;

    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        \Magento\Framework\Data\Helper\PostHelper $postDataHelper,
        UrlFinderInterface $urlFinder,
        UrlHelper $urlHelper,
        \Magento\Framework\Url\ModifierInterface $modifier,
        array $data = []
    ) {
        $this->urlFinder = $urlFinder;
        $this->urlHelper = $urlHelper;
        $this->urlModifier = $modifier;

        parent::__construct($context, $postDataHelper, $data);
    }

    public function beforeGetTargetStorePostData(
        \Magento\Store\Model\Store $store,
        $data = []
    ) {
        $urlRewrite = $this->urlFinder->findOneByData([
            UrlRewrite::TARGET_PATH => $this->trimSlashInPath($this->_request->getPathInfo()),
            UrlRewrite::STORE_ID => $store->getId(),
        ]);
        \Zend_Debug::dump($this->urlModifier->execute( $urlRewrite->getRequestPath()));
        if ($urlRewrite) {
            $data[ActionInterface::PARAM_NAME_URL_ENCODED] = $this->urlHelper->getEncodedUrl(
                $this->trimSlashInPath($this->_urlBuilder->getUrl($urlRewrite->getRequestPath()))
            );
        }
        return [$store, $data];
    }

    /**
     * @param string $path
     * @return string
     */
    private function trimSlashInPath($path)
    {
        return trim($path, '/');
    }

    public function getTargetStorePostData(\Magento\Store\Model\Store $store, $data = [])
    {
        list($store, $data) = $this->beforeGetTargetStorePostData($store, $data);
        return parent::getTargetStorePostData($store, $data); // TODO: Change the autogenerated stub
    }
}