<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product Chooser for "Product Link" Cms Widget Plugin
 */
namespace AAllen\Showcase\Block\Product\Widget;

use Magento\Backend\Block\Template;
use Magento\CatalogWidget\Block\Product\Widget\Conditions;
use Magento\Framework\Data\Form\Element\AbstractElement;
use Magento\Framework\Data\Form\Element\Renderer\RendererInterface;

/**
 * Class MultiConditions
 */
class MultiConditions extends Conditions implements RendererInterface
{
    public function __construct(
        Template\Context $context,
        \Magento\Framework\Data\Form\Element\Factory $elementFactory,
        \Magento\Rule\Block\Conditions $conditions,
        \Magento\CatalogWidget\Model\Rule $rule,
        \Magento\Framework\Registry $registry,
        array $data = [])
    {
        parent::__construct($context, $elementFactory, $conditions, $rule, $registry, $data);
    }

    protected function _construct()
    {
        //$this->rule->getConditions()->setData('id', 3);

        $this->rule->getConditions()->setData('prefix', 'conditions');

        $widget = $this->registry->registry('current_widget_instance');
        if ($widget) {
            $widgetParameters = $widget->getWidgetParameters();
            if (isset($widgetParameters['conditions'])) {
                //$widgetParameters['conditions'] = [1 => $widgetParameters['conditions'][1], '1--1' => $widgetParameters['conditions']['1--1']];
                //\Zend_Debug::dump($widgetParameters);
                $this->rule->loadPost($widgetParameters, 'conditions');
            }
        }
        \Zend_Debug::dump($this->rule->getConditions()->getData('conditions'));

        //parent::_construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getInputHtml()
    {
        $this->rule->getConditions()->setData('prefix', 'conditions');
        $widget = $this->registry->registry('current_widget_instance');
        if ($widget)
            \Zend_Debug::dump($widget->getWidgetParameters());
        //$this->rule->getConditions()->setData('id', 3);

        $this->input = $this->elementFactory->create('text');
        $this->input->setRule($this->rule)->setRenderer($this->conditions);
        return $this->input->toHtml();
    }
}
