<?php


/**
 * Product Chooser for "Product Link" Cms Widget Plugin
 */
namespace AAllen\Showcase\Block\Product\Widget;

use Magento\Backend\Block\Template\Context;
use Magento\CatalogWidget\Block\Product\Widget\Conditions;
use Magento\Framework\Data\Form\Element\Renderer\RendererInterface;

/**
 * Class MultiConditions
 */
class MultiConditions extends Conditions implements RendererInterface
{

    protected function _construct()
    {
        $this->_template = 'product/widget/js.phtml';

        parent::_construct(); // TODO: Change the autogenerated stub
    }

    public function getHtmlId()
    {
        return 'multiconditions1';
    }

}
