<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product Chooser for "Product Link" Cms Widget Plugin
 */
namespace AAllen\Showcase\Block\Product\Widget;

use Magento\Backend\Block\Template;
use Magento\CatalogWidget\Block\Product\Widget\Conditions;
use Magento\Framework\Data\Form\Element\AbstractElement;
use Magento\Framework\Data\Form\Element\Renderer\RendererInterface;

/**
 * Class MultiConditions
 */
class MultiConditions extends Conditions implements RendererInterface
{

    protected function _construct()
    {
        $this->rule->getConditions()->setData('id', 1);

        $widget = $this->registry->registry('current_widget_instance');
        if ($widget) {
            $widgetParameters = $widget->getWidgetParameters();
            if (isset($widgetParameters['conditions'])) {
                $widgetParameters['conditions'] = [1 => $widgetParameters['conditions'][1], '1--1' => $widgetParameters['conditions']['1--1']];
                //\Zend_Debug::dump($widgetParameters);
                $this->rule->loadPost($widgetParameters);
            }
        }

        //parent::_construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getInputHtml()
    {
        $widget = $this->registry->registry('current_widget_instance');
        if ($widget)
            \Zend_Debug::dump($widget->getWidgetParameters());
        $this->rule->getConditions()->setData('id', 1);

        $this->input = $this->elementFactory->create('text');
        $this->input->setRule($this->rule)->setRenderer($this->conditions);
        return $this->input->toHtml();
    }
}
